### ISSUE TITLE
Kodular error on page load

### ISSUE THREAD

**Issue by catpawzz** [Sumit1334/Mary-Dialog#2]
When I load a page with the MaryDialog extention I sometimes get this error: 
![image](https://user-images.githubusercontent.com/89903745/196038723-26165f45-724c-48dd-8d24-261e08cb2a3a.png)
Is it a mistake on my side, or a extention bug?
Thanks in advance :)

**Comment by yumithecat** [comment]
Now it also says this since i added a is shown 
![Screenshot_20221016-164128.jpg](https://user-images.githubusercontent.com/89903745/196041796-2f731ed1-e72d-47de-8115-39c9c406ed66.jpg)

**Comment by catpawzz** [comment]
So after remaking everything and making sure everything is really alright, the bug seems to be gone for now. Don't be like me and directly post an issue xD

**Comment by iamwsumit** [comment]
This was not a bug, you were just trying to access a dialog with invalid id.

**Comment by catpawzz** [comment]
It still does happen randomly sometimes tho
